[pytest]
# --html: Generates the report
# --capture=no: Allows you to see print/log statements in real-time
# --tb=short: Keeps the error tracebacks clean and readable
addopts = --html=reports/report.html --self-contained-html --capture=no --tb=short

# Define where your tests are located
testpaths = security_automation/tests

# Log Configuration (Internal Python logging)
log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)
log_cli_date_format=%Y-%m-%d %H:%M:%S