- name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        # Add the folder name before requirements.txt
        pip install -r security_automation/requirements.txt

    - name: Run Security Tests
      run: |
        # Run pytest from the root, targeting the folder
        python -m pytest security_automation --html=security_automation/reports/report.html --self-contained-html
      continue-on-error: true

    - name: Upload Security Report
      uses: actions/upload-artifact@v4
      with:
        name: security-scan-report
        # Ensure the path matches where pytest saves the report
        path: security_automation/reports/
