name: Security Automation Suite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Start OWASP Juice Shop (Target Application)
      run: |
        # Run Juice Shop in the background on port 3000
        docker run --rm -d -p 3000:3000 bkimminich/juice-shop
        # Wait for the server to start (Health Check)
        echo "Waiting for Juice Shop to wake up..."
        timeout 60s bash -c 'until curl -s localhost:3000; do sleep 5; done'
        echo "Juice Shop is UP and running on localhost:3000"

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Install Dependencies
      run: |
        # Pointing to your specific folder path
        pip install -r security_automation/requirements.txt

    - name: Run Security Tests
      run: |
        # Running from root, targeting your folder
        python -m pytest security_automation --html=security_automation/reports/report.html --self-contained-html
      continue-on-error: true

    - name: Upload Security Report
      uses: actions/upload-artifact@v4
      with:
        name: security-scan-report
        path: security_automation/reports/
